<?php

namespace app\modules\api\v1\models;

use Yii;
use yii\caching\TagDependency;
use yii\db\ActiveQuery;

/**
 * This is the model class for table "posts".
 *
 * @property int $id
 * @property string $title
 * @property string $content
 * @property int $category_id
 *
 * @property Categories $category
 */
class Posts extends \yii\db\ActiveRecord implements Cacheable
{
    public static function getCachePrefix(): string
    {
        return 'posts_list_';
    }

    public static function getTagDependencyLabel(): string
    {
        return 'posts_cache';
    }

    public static function tableName(): string
    {
        return 'posts';
    }

    public function rules(): array
    {
        return [
            [['category_id'], 'required'],
            [['category_id'], 'integer'],
            [['title', 'content'], 'string', 'max' => 255],
            [
                ['category_id'],
                'exist',
                'skipOnError' => true,
                'targetClass' => Categories::className(),
                'targetAttribute' => ['category_id' => 'id']
            ],
        ];
    }

    public function attributeLabels(): array
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'content' => 'Content',
            'category_id' => 'Category ID',
        ];
    }

    public function getCategory(): ActiveQuery
    {
        return $this->hasOne(Categories::class, ['id' => 'category_id']);
    }

    public function afterSave($insert, $changedAttributes)
    {
        if ($insert || isset($changedAttributes['category_id'])) {
            TagDependency::invalidate(Yii::$app->cache, Categories::getTagDependencyLabel());
        }
        TagDependency::invalidate(Yii::$app->cache, self::getTagDependencyLabel());
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        TagDependency::invalidate(Yii::$app->cache, Categories::getTagDependencyLabel());
        TagDependency::invalidate(Yii::$app->cache, self::getTagDependencyLabel());
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
}
