version: '2'
services:
  web:
    image: yiisoftware/yii2-php:7.1-apache
    depends_on:
      - db
      - composer
      - migration
    volumes:
      - ./:/app:delegated
    ports:
      - '8000:80'
    tty: true
  composer:
    image: composer
    volumes:
      - ./:/app:delegated
    command:
      - /app/composer.sh
  migration:
    image: williamyeh/dummy
    volumes:
      - ./:/app:delegated
    command:
      - /app/wait.sh
    depends_on:
      - db
  db:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: secretpassroot
        MYSQL_USER: db_user
        MYSQL_PASSWORD: secretpass
        MYSQL_DATABASE: yii